controller:

  replicaCount: 1

  service:
    type: LoadBalancer

  admissionWebhooks:
    enabled: true

  metrics:
    enabled: true

  ingressClassResource:
    default: true

defaultBackend:
  enabled: true
